import { Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";
import Container from "@/components/container";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative">
          <Sidebar />
          <div className="p-16">
            <Container>{children}</Container>
          </div>
        </main>
      </body>
    </html>
  );
}
